---
title: "OHM"
author: "Christopher Tsz Hin Choi"
date: "2024-03-19"
output: html_document
---

#### For example purposes only
* CONFIDENTIAL PLOT NUMBERS HAVE BEEN REDACTED

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages(c('circular', 'lidR', 'viridis', 'rgl', 'fpc', 'VoxR'))

require(circular)
require(lidR)
require(viridis)
require(rgl)
require(fpc)
```

```{r}
library(circular)
library(lidR)
library(viridis)
# library(rgl)
library(fpc)
library(VoxR)
library(dplyr)
library(stringr)
library(DBI)
library(RSQLite)
# devtools::install_github("lmterryn/ITSMe", build_vignettes = TRUE)
# library(ITSMe)
```
###Source OHM functions
```{r}
source("OHM-master/R/2024_OHM_FUN.R")

```

###Data
```{r}
## point to TLS data
files.trunk <- list.files("Data/TLS_Scans/Trees/All_Standing_Trees", pattern="trunk.csv", full.names = TRUE, recursive=TRUE)

files.branch <- list.files("Data/TLS_Scans/Trees/All_Standing_Trees", pattern="branch.csv", full.names = TRUE, recursive=TRUE)

tree.ID <- list.dirs("Data/TLS_Scans/Trees/All_Standing_Trees", full.names = FALSE)
##################
# #Making a dataframe of files for the tree components
# combine.files<-function(treeID, trunk, branch) {
#   treeID = tree.ID[-1]
# 
# 
#   plot.ID <- data.frame(ID = tree.ID[-1])
# 
#   trunk.tree.ID <- data.frame(trunk.filename = files.trunk,
#                               ID = t(data.frame(ID = strsplit(files.trunk,  split = c('/')))[2,])) |>
#     setNames(c('trunk.filename', 'ID'))
# 
#   branch.tree.ID <- data.frame(branch.filename = files.branch,
#                                ID = t(data.frame(ID = strsplit(files.branch,  split = c('/')))[2,])) |>
#     setNames(c('branch.filename', 'ID'))
# 
# 
#   data = merge(plot.ID, trunk.tree.ID, by = 'ID')
# 
#   data2 = merge(data, branch.tree.ID, by = 'ID', all.x = T)
# 
# 
#   data = merge(plot.ID, trunk.tree.ID, by = 'ID') |>
#     dplyr::left_join(branch.tree.ID, by = 'ID')
# 
#   data = dplyr::full_join(plot.ID, branch.tree.ID)
# 
# 
#   ###############3
#   long_df <- reshape(df, direction = "long",
#         varying = which(!names(df) %in% c("A", "B")),
#         v.names = "value",
#         timevar = "year",
#         times = names(df)[!(names(df) %in% c("A", "B"))],
#         ids = NULL,
#         new.row.names = 1:(length(which(!names(df) %in% c("A", "B"))) * nrow(df)))
# 
# 
#   for(i in tree.ID){
#     print(i)
#   }
# 
#   trunk.tree.ID = list()
# 
#   for(i in files.trunk){
#     trunk.tree.ID.2 = c(trunk.tree.ID, substr(i, '_'))
#   }
# 
# 
#   tree.ID.df<- data.frame(treeID = tree.ID,
#                           trunk = files.trunk)
# 
# }
# 
###################

# REF_SPECIES table
REF_SPECIES <- read.csv('Data/FIADB_REFERENCE/REF_SPECIES.csv')



######################################################
## SQLITE database
######################################################

#database path
sqlite_path <- file.path('Data/SQLite_FIADB_CO/SQLite_FIADB_CO.db')

## connection to db
conn <- DBI::dbConnect(RSQLite::SQLite(), sqlite_path)

DBI::dbListTables(conn)
# DBI::dbListFields(conn, 'TREE')


## Tree table
######################################################
TREE <- DBI::dbReadTable(conn, "TREE")


## Disconnect from db
DBI::dbDisconnect(conn)
```

```{r}
files<-data.frame(treeID=tree.ID[-1],
                  trunk=files.trunk,
                  branch=files.branch)

```

```{r}
#Read in TLS data
ohm.files<-read.csv.ohm.input(files[4,])

#We can split the files into trunk and biomass elements
trunk <- ohm.files[[1]]
branch <- ohm.files[[2]]

```

```{r}
ohm.biomass <- function(files){
  
  ## Final structure of output table
  output.table = data.frame(treeID = character(),
                             trunk = double(),
                             branch = double(),
                             total = double(),
                             z = double(),
                             dbh = double() #DBH
                             )
  
  
  
  # for (i in 39:40){
  for (i in 1:nrow(files)){
    
    ## dbh
    filtered.fitted.circles.table = data.frame(dbh = double()    ## tree height

                             )
    height.table = data.frame(z = double())
    
    ohm.files<-read.csv.ohm.input(files[i,])
    
    #We can split the files into trunk and biomass elements
    trunk <- ohm.files[[1]]
    branch <- ohm.files[[2]]
    
    
    OHM.output<-OHM.tree(trunk = trunk,
                     branch = branch,
                     sg=0.4,
                     interval = 0.1, buff = 0.1, outlier_pct = 20,
                     vox.res=0.1, vol.correction=1)
    
    treeID.table = data.frame(treeID = files[i,]$treeID)
    
    ## Reduce biomass less than 1 to 0 since it is placeholder data
    if(OHM.output$biomass$trunk < 0.3){
      OHM.output$biomass$trunk = 0
       OHM.output$trunk.volume$vol = 0
    }
    if(OHM.output$biomass$branch < 0.1){
      OHM.output$biomass$branch = 0
      OHM.output$branch.volume$z = 0
    }
    
    OHM.output$biomass$total = OHM.output$biomass$trunk + OHM.output$biomass$branch
    
    
    ## Find tree height
    if (max(OHM.output$all.circle.fits$z) > 0.1){
      height.table = rbind(height.table, max(OHM.output$all.circle.fits$z))
      
      names(height.table) = 'z'
      
    } else if (max(OHM.output$all.circle.fits$z) <= 0.1){
      height.table = rbind(height.table, data.frame(z = c(0)))
      
      names(height.table) = 'z'
    }
    
     
    
    ## Find dbh
    if(max(OHM.output$filtered.circle.fits$z) >= 1.2){
      
      # print('T1')
      
      filtered.fitted.circles.table = rbind(filtered.fitted.circles.table, OHM.output$filtered.circle.fits) |>
        dplyr::filter(z == "1.2") |> # 1.2m = 4.5ft = dbh
        dplyr::transmute(dbh = r*2) # radius * 2 == diameter
      
      
    } else if (max(OHM.output$filtered.circle.fits$z) < 1.2){
      # print('T2')
      filtered.fitted.circles.table = rbind(filtered.fitted.circles.table, data.frame(dbh = c(0)))
      
    }
    
    
    
    
    output.table = rbind(output.table, cbind(treeID.table, # treeID
                                             OHM.output$biomass, #  biomass
                                             height.table, # Tree height
                                             
                                             filtered.fitted.circles.table # dbh
                                             ))
    
    print(treeID.table, 'completed')
    
    
  }
  
  return(output.table)
  
}



TLS.biomass <- ohm.biomass(files)





```


```{r}
## Add plot and tree reference numbers
TLS.biomass2 <- TLS.biomass |>
  dplyr::mutate(STATECD = case_when((grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 8,
                                    
                                    .default = NA
                                    ),
                
                COUNTYCD = case_when((grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 49,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 57,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 69,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 69,
                                    
                                    .default = NA
                                    ),
                
                PLOT = case_when((grepl("9999", treeID, fixed = T)) == T ~ 20,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 20,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 37,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 37,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 37,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 38,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 38,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 66,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 66,
                                 
                                    (grepl("9999", treeID, fixed = T)) == T ~ 3023,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 3023,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 3001,
                                    .default = NA),
                SUBP = case_when((grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 4,
                                    
                                 
                                    (grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 2,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 3,
                                    
                                 
                                    (grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 4,
                                    
                                    (grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 2,
                                 
                                    (grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    (grepl("9999", treeID, fixed = T)) == T ~ 4,
                                 
                                    (grepl("9999", treeID, fixed = T)) == T ~ 1,
                                    .default = NA),
                
                TREE = as.numeric(stringr::str_sub(treeID, -2, -1))

  )

# TLS.biomass2

head(TLS.biomass2)
```

```{r}
TLS.carbon <- TLS.biomass2 |>
  ## Convert confidential plot numbers to public numbers for joining with TREE table
  dplyr::mutate(PLOT = dplyr::case_when(PLOT == 3023 ~ 9999,
                                             PLOT == 3001 ~ 9999,
                                             PLOT == 149 ~ 9999,
                                             PLOT == 104 ~ 9999,
                                             PLOT == 3031 ~ 9999,
                                             PLOT == 83 ~ 9999,
                                             PLOT == 66 ~ 9999,
                                             PLOT == 38 ~ 9999,
                                             PLOT == 37 ~ 9999,
                                             PLOT == 20 ~ 9999,
                                             PLOT == 3040 ~ 9999)) |>
  ## Add SPCD from TREE table
  dplyr::left_join(TREE |> dplyr::filter(INVYR > 2008) |> dplyr::select(STATECD, COUNTYCD, PLOT, SUBP, TREE, SPCD) , by = c('STATECD', 'COUNTYCD', 'PLOT', 'SUBP', 'TREE')) |>
  ## Join with REF_SPECIES table for species specific carbon values
  dplyr::left_join(REF_SPECIES, by = 'SPCD') |>
  dplyr::mutate(CARBON_AG = dplyr::if_else(is.na(CARBON_RATIO_LIVE) == F, 
                                           total * CARBON_RATIO_LIVE,
                                           total * 0.5))
  
  # dplyr::mutate(CARBON_AG = dplyr::case_when(is.na(CARBON_RATIO_LIVE) == F) ~ total* CARBON_RATIO_LIVE,
  #               .default = total * 0.5)

TLS.carbon
```


Output data
```{r}
write.csv(TLS.carbon, 'Data/TLS_Carbon_20250129.csv')

```




######################################################################################################################
######################################################################################################################







## Visualize trees
```{r}
# 
# # Plot
# plot3d( 
#   x=trunk$X, y=trunk$Y, z=trunk$Z, 
#   col = 'black', 
#   type = 's', 
#   radius = .1,
#   xlab="X", ylab="Y", zlab="Z")


```


## Estimate Tree Volume and Biomass with OHM
```{r}
OHM.output<-OHM.tree(trunk = trunk,
                     branch = branch,
                     sg=0.4,
                     interval = 0.1, buff = 0.1, outlier_pct = 20,
                     vox.res=0.1, vol.correction=1)

```


## Checking outputs

###Trunk Radius fit
```{r}
#Look at the trunk radius fits
plot(OHM.output$all.circle.fits$r, OHM.output$all.circle.fits$z, col="grey", main='Trunk Radius Fits',
     ylab='Height (m)', xlab= "Radius (m)")
lines(OHM.output$filtered.circle.fits$r, OHM.output$filtered.circle.fits$z, col="forestgreen")

```


### Cumulatve component biomass
```{r}
plot(OHM.output$trunk.volume$z, cumsum(OHM.output$trunk.volume$vol), col="white", xlab='Height (m)', ylab= "Volume (m^3)", 
     main="Cumulative Tree /n Component Volume",
     sub = "(brown = trunk; green = crown)")
lines(OHM.output$trunk.volume$z, cumsum(OHM.output$trunk.volume$vol), col="brown")
lines(OHM.output$branch.volume$z, cumsum(OHM.output$branch.volume$vol.log), col="forestgreen")

```

## Biomass
```{r}
print(paste("Total tree biomass estimate is",
            OHM.output$biomass[3]
))
print(paste("Trunk tree biomass estimate is",
            OHM.output$biomass[1]
))
print(paste("Branch tree biomass estimate is",
            OHM.output$biomass[2]
))

```
0.000125663706143592

```{r}
max(OHM.output$filtered.circle.fits[,1])
OHM.output$filtered.circle.fits[,1]
```
